default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_38865_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_38865_test

production:
 <<: *default
  database: furima_38865_production
  username: furima_38865
  password: <%= ENV['FURIMA_38865_DATABASE_PASSWORD'] %>
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>